/**
 * Firebase Storage Utility
 * Uploads images generated by the Autonomous AI engine to Firebase Storage
 * and returns a permanent public download URL for storage in MongoDB.
 *
 * Auth: Uses the portfolio-nabaraj service account JSON via env vars.
 */

import { initializeApp, getApps, cert, type App } from "firebase-admin/app";
import { getStorage } from "firebase-admin/storage";
import * as path from "path";
import * as fs from "fs";

let app: App | null = null;

function getAppInstance(): App {
  if (app) return app;

  const apps = getApps();
  if (apps.length > 0) {
    app = apps[0]!;
    return app;
  }

  // Load service account from file path
  const serviceAccountPath = process.env.FIREBASE_SERVICE_ACCOUNT_PATH;
  if (!serviceAccountPath) {
    throw new Error("FIREBASE_SERVICE_ACCOUNT_PATH env var is not set.");
  }

  const resolvedPath = path.resolve(process.cwd(), serviceAccountPath);
  if (!fs.existsSync(resolvedPath)) {
    throw new Error(`Firebase service account file not found at: ${resolvedPath}`);
  }

  const serviceAccount = JSON.parse(fs.readFileSync(resolvedPath, "utf-8"));

  app = initializeApp({
    credential: cert(serviceAccount),
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  });

  return app;
}

/**
 * Uploads an image buffer to Firebase Storage under the given path.
 * Returns the permanent public download URL.
 *
 * @param imageBuffer  - Raw image data (e.g. from Cloudflare AI)
 * @param destination  - Path inside the bucket, e.g. "autonomous/articles/my-slug.jpg"
 * @param contentType  - MIME type, defaults to "image/jpeg"
 */
export async function uploadImageToFirebase(
  imageBuffer: ArrayBuffer | Buffer,
  destination: string,
  contentType: string = "image/jpeg"
): Promise<string> {
  const buffer = Buffer.isBuffer(imageBuffer)
    ? imageBuffer
    : Buffer.from(imageBuffer);

  const fallbackDataUrl = `data:${contentType};base64,${buffer.toString("base64")}`;

  try {
    const firebaseApp = getAppInstance();
    const storage = getStorage(firebaseApp);

    // List candidate bucket names to try
    const candidates = [
      process.env.FIREBASE_STORAGE_BUCKET,
      "portfolio-nabaraj.appspot.com",
      "portfolio-nabaraj.firebasestorage.app",
      "portfolio-nabaraj",
    ].filter(Boolean) as string[];

    let lastError: any = null;

    for (const bucketName of candidates) {
      try {
        const bucket = storage.bucket(bucketName);
        const file = bucket.file(destination);

        await file.save(buffer, {
          metadata: {
            contentType,
            cacheControl: "public, max-age=31536000",
          },
        });

        try {
          await file.makePublic();
        } catch (mErr) {
          console.warn(`[Firebase Storage] makePublic notice on ${bucketName}:`, mErr);
        }

        const publicUrl = `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(destination)}?alt=media`;
        console.log(`[Firebase Storage] Uploaded successfully to bucket ${bucketName}: ${publicUrl}`);
        return publicUrl;
      } catch (err: any) {
        lastError = err;
        console.warn(`[Firebase Storage] Bucket attempt '${bucketName}' failed:`, err.message || err);
      }
    }

    console.warn("[Firebase Storage] All Firebase bucket candidates failed. Falling back to Data URL representation:", lastError?.message);
    return fallbackDataUrl;
  } catch (globalErr: any) {
    console.error("[Firebase Storage] Error in uploadImageToFirebase:", globalErr.message || globalErr);
    return fallbackDataUrl;
  }
}

/**
 * Context-Aware Visual Concept & Prompt Synthesizer
 * Inspects article title, keywords, and category tag to build an accurate topic-tailored prompt.
 */
export function buildTopicContextualPrompt(title: string = "", keywords: string[] = [], tag: string = ""): string {
  const combinedText = `${title} ${keywords.join(" ")} ${tag}`.toLowerCase();

  let conceptVisual = "isometric software architecture nodes, distributed node cluster, glowing microchip interconnects";
  let colorTheme = "warm amber (#C85A17) and deep purple (#5B4A8A) neon lighting";

  if (combinedText.includes("quantum") || combinedText.includes("qubit") || combinedText.includes("hardware")) {
    conceptVisual = "3D quantum circuit lattice, qubit entanglement nodes with glowing sapphire and violet photon trails, futuristic quantum computer processor core";
    colorTheme = "electric sapphire blue, cyan, and neon violet glows";
  } else if (combinedText.includes("agent") || combinedText.includes("swarm") || combinedText.includes("autonomous") || combinedText.includes("krrishmay")) {
    conceptVisual = "futuristic multi-agent AI swarm network graph, glowing inter-agent neural nodes with amber data transmission lines, autonomous agent cluster";
    colorTheme = "vibrant amber (#C85A17) and dark charcoal slate background";
  } else if (combinedText.includes("rag") || combinedText.includes("vector") || combinedText.includes("embedding") || combinedText.includes("llm") || combinedText.includes("transformer") || combinedText.includes("nlp")) {
    conceptVisual = "high-tech 3D semantic vector embedding space, multi-dimensional data cluster points connected by laser light paths, transformer attention mechanism matrix";
    colorTheme = "emerald green, glowing cyan, and deep obsidian background";
  } else if (combinedText.includes("vision") || combinedText.includes("robot") || combinedText.includes("spatial") || combinedText.includes("lidar")) {
    conceptVisual = "autonomous AI vision perception grid, 3D LiDAR point cloud wireframe overlay on robotic hardware, spatial neural network sensor array";
    colorTheme = "laser orange and glowing white wireframe grid";
  }

  const subjectKeywords = keywords.slice(0, 4).join(", ") || "Artificial Intelligence Architecture";

  return `Professional 16:9 technology editorial banner illustrating "${title.slice(0, 50)}". Subject: ${subjectKeywords}. Visual elements: ${conceptVisual}. Color palette: ${colorTheme}. Cinema 4D render, clean modern tech aesthetic, ultra detailed, cinematic lighting, 8k resolution. No text.`;
}

/**
 * Generates an artistic topic-matched SVG tech banner buffer as a 100% reliable fallback
 */
function createSvgTechBanner(title: string, keywords: string[], tag?: string): Buffer {
  const safeTitle = title.replace(/[<>&"]/g, "").trim() || "Autonomous AI System";
  const subjectTag = (tag || keywords[0] || "AI SPECIFICATION").toUpperCase();
  const keywordsSub = keywords.slice(0, 3).join(" • ") || "Autonomous AI System";

  // Wrap long titles into 2 lines if needed
  let line1 = safeTitle;
  let line2 = "";
  if (safeTitle.length > 32) {
    const spaceIdx = safeTitle.indexOf(" ", 25);
    if (spaceIdx !== -1) {
      line1 = safeTitle.slice(0, spaceIdx);
      line2 = safeTitle.slice(spaceIdx + 1);
    }
  }

  const combinedText = `${safeTitle} ${keywordsSub}`.toLowerCase();
  let graphicPattern = "";

  if (combinedText.includes("quantum") || combinedText.includes("qubit")) {
    graphicPattern = `
      <ellipse cx="1020" cy="360" rx="160" ry="80" fill="none" stroke="#C85A17" stroke-width="2" opacity="0.4" transform="rotate(-25 1020 360)" />
      <ellipse cx="1020" cy="360" rx="160" ry="80" fill="none" stroke="#5B4A8A" stroke-width="2" opacity="0.4" transform="rotate(35 1020 360)" />
      <circle cx="1020" cy="360" r="14" fill="#C85A17" />
      <circle cx="940" cy="320" r="8" fill="#5B4A8A" />
      <circle cx="1100" cy="400" r="8" fill="#E87D3E" />
    `;
  } else if (combinedText.includes("agent") || combinedText.includes("swarm") || combinedText.includes("network")) {
    graphicPattern = `
      <line x1="900" y1="280" x2="1020" y2="200" stroke="#C85A17" stroke-width="2" opacity="0.5" />
      <line x1="1020" y1="200" x2="1140" y2="300" stroke="#C85A17" stroke-width="2" opacity="0.5" />
      <line x1="900" y1="280" x2="1060" y2="420" stroke="#C85A17" stroke-width="2" opacity="0.5" />
      <line x1="1140" y1="300" x2="1060" y2="420" stroke="#C85A17" stroke-width="2" opacity="0.5" />
      <circle cx="900" cy="280" r="12" fill="#C85A17" />
      <circle cx="1020" cy="200" r="16" fill="#E87D3E" />
      <circle cx="1140" cy="300" r="14" fill="#5B4A8A" />
      <circle cx="1060" cy="420" r="18" fill="#C85A17" />
    `;
  } else {
    graphicPattern = `
      <rect x="900" y="220" width="180" height="120" rx="12" fill="#1E1E1E" stroke="#C85A17" stroke-width="2" opacity="0.8" />
      <rect x="960" y="300" width="180" height="120" rx="12" fill="#281A10" stroke="#5B4A8A" stroke-width="2" opacity="0.8" />
      <circle cx="990" cy="280" r="6" fill="#C85A17" />
      <circle cx="1050" cy="360" r="6" fill="#E87D3E" />
    `;
  }

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720" width="1280" height="720">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#0F0F0F" />
        <stop offset="50%" stop-color="#1A1A1A" />
        <stop offset="100%" stop-color="#24160E" />
      </linearGradient>
      <linearGradient id="accent" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#C85A17" />
        <stop offset="100%" stop-color="#E87D3E" />
      </linearGradient>
    </defs>
    <rect width="1280" height="720" fill="url(#bg)" />
    
    <!-- Background glows -->
    <circle cx="1050" cy="300" r="320" fill="#C85A17" opacity="0.14" filter="blur(50px)" />
    <circle cx="200" cy="550" r="280" fill="#5B4A8A" opacity="0.15" filter="blur(60px)" />
    
    <!-- Tech Grid Lines -->
    <g opacity="0.07" stroke="#FFFFFF" stroke-width="1">
      <path d="M0 120 H1280 M0 240 H1280 M0 360 H1280 M0 480 H1280 M0 600 H1280" />
      <path d="M160 0 V720 M320 0 V720 M480 0 V720 M640 0 V720 M800 0 V720 M960 0 V720 M1120 0 V720" />
    </g>

    <!-- Topic Graphic Pattern -->
    ${graphicPattern}

    <!-- Category Tag Badge -->
    <rect x="80" y="80" width="220" height="36" rx="18" fill="url(#accent)" />
    <text x="190" y="103" font-family="monospace" font-size="12" font-weight="bold" fill="#FFFFFF" text-anchor="middle" letter-spacing="2">${subjectTag}</text>

    <!-- Title Lines -->
    <text x="80" y="280" font-family="sans-serif" font-size="44" font-weight="bold" fill="#FFFFFF">${line1}</text>
    ${line2 ? `<text x="80" y="345" font-family="sans-serif" font-size="44" font-weight="bold" fill="#FFFFFF">${line2}</text>` : ""}
    
    <!-- Subtitle / Keywords -->
    <text x="80" y="${line2 ? 415 : 355}" font-family="sans-serif" font-size="22" fill="#C85A17">${keywordsSub}</text>
    
    <!-- Footer Branding -->
    <text x="80" y="620" font-family="monospace" font-size="14" fill="#8F8F8F">NABARAJ KC • AUTONOMOUS RESEARCH PLATFORM</text>
  </svg>`;

  return Buffer.from(svg, "utf-8");
}

/**
 * Generates a cover image matched to the exact topic of the article/paper
 * using Cloudflare AI, Pollinations AI, or SVG Engine, and uploads to Firebase Storage.
 */
export async function generateAndUploadCoverImage(
  keywords: string[],
  slug: string,
  folder: string = "autonomous/articles",
  title?: string,
  tag?: string
): Promise<string> {
  const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;
  const apiToken = process.env.CLOUDFLARE_API_TOKEN;

  // Synthesize ultra-specific topic visual prompt
  const imagePrompt = buildTopicContextualPrompt(title, keywords, tag);
  console.log(`[Firebase Storage] Topic-matched image prompt: "${imagePrompt.slice(0, 100)}..."`);

  // 1. Try Hugging Face AI (Primary High-Quality Model)
  const hfToken = process.env.HUGGINGFACE_API_TOKEN;
  if (hfToken) {
    try {
      console.log("[Firebase Storage] Requesting Hugging Face AI (SDXL) image generation...");
      const hfResponse = await fetch(
        "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0",
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${hfToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ inputs: imagePrompt }),
        }
      );

      if (hfResponse.ok) {
        const imageBuffer = await hfResponse.arrayBuffer();
        const destination = `${folder}/${slug}.jpg`;
        const url = await uploadImageToFirebase(imageBuffer, destination, "image/jpeg");
        console.log(`[Firebase Storage] Hugging Face AI topic cover uploaded: ${url}`);
        return url;
      } else {
        console.warn(`[Firebase Storage] Hugging Face AI failed with status: ${hfResponse.status}`);
      }
    } catch (err: any) {
      console.warn("[Firebase Storage] Hugging Face AI attempt failed:", err.message);
    }
  }

  // 2. Try Cloudflare AI
  if (accountId && apiToken) {
    try {
      console.log("[Firebase Storage] Requesting Cloudflare AI SDXL Lightning generation...");
      const cfResponse = await fetch(
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/@cf/bytedance/stable-diffusion-xl-lightning`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${apiToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ prompt: imagePrompt }),
        }
      );

      if (cfResponse.ok) {
        const imageBuffer = await cfResponse.arrayBuffer();
        const destination = `${folder}/${slug}.jpg`;
        const url = await uploadImageToFirebase(imageBuffer, destination, "image/jpeg");
        console.log(`[Firebase Storage] Cloudflare AI topic cover uploaded: ${url}`);
        return url;
      }
    } catch (err: any) {
      console.warn("[Firebase Storage] Cloudflare AI attempt failed:", err.message);
    }
  }

  // 3. Try Pollinations AI Engine
  try {
    console.log("[Firebase Storage] Requesting Pollinations AI topic image generation...");
    const pollinationsUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(imagePrompt)}?width=1280&height=720&nologo=true`;
    const polRes = await fetch(pollinationsUrl);
    if (polRes.ok) {
      const buffer = await polRes.arrayBuffer();
      const destination = `${folder}/${slug}.jpg`;
      const url = await uploadImageToFirebase(buffer, destination, "image/jpeg");
      console.log(`[Firebase Storage] Pollinations AI topic cover uploaded: ${url}`);
      return url;
    }
  } catch (err: any) {
    console.warn("[Firebase Storage] Pollinations AI attempt failed:", err.message);
  }

  // 3. Fallback Topic-Matched SVG Tech Banner
  console.log("[Firebase Storage] Generating Topic-Matched SVG Tech Banner fallback...");
  const svgBuffer = createSvgTechBanner(title || slug, keywords, tag);
  const destination = `${folder}/${slug}.svg`;
  const url = await uploadImageToFirebase(svgBuffer, destination, "image/svg+xml");
  console.log(`[Firebase Storage] Topic-Matched SVG Banner uploaded to Firebase: ${url}`);
  return url;
}
