import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import clientPromise from "@/lib/mongodb";
import { deepResearchTopic, TavilyResult } from "@/lib/rag-engine";
import { generateAndUploadCoverImage } from "@/lib/firebase-storage";
import { shortenTitle } from "@/lib/title-utils";
import { cookies } from "next/headers";
import { getArticleWriterPrompt, getResearchWriterPrompt } from "@/lib/ai-prompts";

async function getApiKey(name: string, envKey: string): Promise<string> {
  try {
    const client = await clientPromise;
    const db = client.db();
    const record = await db.collection("apikeys").findOne({ name });
    return record?.value || process.env[envKey] || "";
  } catch {
    return process.env[envKey] || "";
  }
}

async function generateWithGemini(prompt: string, apiKey: string): Promise<string> {
  const genAI = new GoogleGenerativeAI(apiKey);
  const models = ["gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro"];
  for (const modelName of models) {
    try {
      const model = genAI.getGenerativeModel({ model: modelName });
      const result = await model.generateContent(prompt);
      return result.response.text();
    } catch (err: any) {
      const msg = (err?.message || "").toLowerCase();
      if (msg.includes("429") || msg.includes("quota") || msg.includes("rate")) continue;
      throw err;
    }
  }
  throw new Error("All Gemini models exhausted");
}

async function generateWithMistral(prompt: string, apiKey: string): Promise<string> {
  const models = ["mistral-small-latest", "mistral-medium-latest", "open-mistral-7b"];
  for (const modelName of models) {
    try {
      const res = await fetch("https://api.mistral.ai/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          model: modelName,
          messages: [{ role: "user", content: prompt }],
          temperature: 0.75, max_tokens: 8000,
        }),
      });
      if (res.status === 429) continue;
      if (!res.ok) throw new Error(`Mistral ${res.status}`);
      const data = await res.json();
      const text = data.choices?.[0]?.message?.content;
      if (text) return text;
    } catch (err: any) {
      if ((err?.message || "").includes("429")) continue;
      throw err;
    }
  }
  throw new Error("All Mistral models exhausted");
}

async function generateContent(prompt: string): Promise<string> {
  const geminiKey = await getApiKey("GEMINI_API_KEY", "GEMINI_API_KEY");
  const mistralKey = await getApiKey("MISTRAL_API_KEY", "MISTRAL_API_KEY");
  try {
    if (geminiKey) return await generateWithGemini(prompt, geminiKey);
  } catch (err: any) {
    console.warn("[GenerateContent] Gemini failed, trying Mistral:", err.message);
  }
  if (mistralKey) return await generateWithMistral(prompt, mistralKey);
  throw new Error("No AI provider available");
}

function parseJSON(raw: string): any {
  if (!raw) return null;

  // Attempt 1: strip markdown code fences
  let cleaned = raw
    .replace(/```json\s*/gi, "")
    .replace(/```\s*/g, "")
    .trim();

  // Attempt 2: extract the outermost JSON object
  const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
  if (jsonMatch) cleaned = jsonMatch[0];

  // Attempt 3: remove JavaScript-style trailing commas before } or ]
  cleaned = cleaned
    .replace(/,\s*}/g, "}")
    .replace(/,\s*]/g, "]");

  try {
    return JSON.parse(cleaned);
  } catch {
    // Attempt 4: Fix control characters & raw linebreaks inside string quotes
    try {
      const sanitized = cleaned
        .replace(/[\x00-\x09\x0B\x0C\x0E-\x1F\x7F]/g, "")
        .replace(/\n(?=[^"]*"*(?:[^"]*"[^"]*")*[^"]*$)/g, "\\n");
      return JSON.parse(sanitized);
    } catch {
      // Attempt 5: Regex extraction fallback
      const getField = (field: string) => {
        const match = raw.match(new RegExp(`"${field}"\\s*:\\s*"([^"\\\\]*(?:\\\\.[^"\\\\]*)*)"`, "i"));
        return match ? match[1].replace(/\\n/g, "\n").replace(/\\"/g, '"') : null;
      };

      const title = getField("title");
      const slug = getField("slug") || title?.toLowerCase().replace(/[^a-z0-9]+/g, "-") || `content-${Date.now()}`;
      const excerpt = getField("excerpt") || getField("abstract");
      const tag = getField("tag") || "AI";

      if (title || slug) {
        return {
          title: title || "AI Content Specification",
          slug: slug.replace(/^-+|-+$/g, ""),
          excerpt: excerpt || "Autonomous research specification generated by Antigravity AI Engine.",
          abstract: excerpt || "Autonomous research specification generated by Antigravity AI Engine.",
          tag,
          keywords: [tag, "AI", "Machine Learning", "Autonomous Systems"],
          date: new Date().toLocaleDateString("en-US"),
          readTime: "6 min read",
          author: "Nabaraj KC",
          content: raw.length > 200 ? raw.replace(/```json[\s\S]*```/g, "").trim() : "",
          publishedAt: new Date().toISOString(),
          generatedBy: "on-demand-ai",
        };
      }

      console.error("[generate-content] JSON parse failed entirely. Raw snippet:", raw.slice(0, 300));
      return null;
    }
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { type = "article", topic, requestedBy = "krrishmay-user", requireAuth = false } = body;

    if (requireAuth) {
      const cookieStore = await cookies();
      const adminToken = cookieStore.get("admin-token")?.value;
      if (adminToken !== process.env.ADMIN_SESSION_TOKEN) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
      }
    }

    if (!topic) {
      return NextResponse.json({ error: "Topic is required" }, { status: 400 });
    }

    const client = await clientPromise;
    const db = client.db();
    const today = new Date().toLocaleDateString("en-US");

    const collection = type === "research" ? "research" : "articles";
    const existing = await db.collection(collection).find({}).sort({ _id: -1 }).limit(20).toArray();
    const existingTitles = existing.map((d: any) => d.title).join(", ");

    const { context, sources } = await deepResearchTopic(topic);

    const isoDate = new Date().toISOString();
    const prompt = type === "research"
      ? getResearchWriterPrompt(topic, context, existingTitles, today, isoDate)
      : getArticleWriterPrompt(topic, context, existingTitles, today, isoDate);

    const raw = await generateContent(prompt);
    let data = parseJSON(raw);

    // If data.content contains nested JSON, unpack the inner markdown string
    if (data && typeof data.content === "string") {
      let cnt = data.content.trim();
      if (cnt.startsWith("```json") || cnt.startsWith("{")) {
        const inner = parseJSON(cnt);
        if (inner && inner.content) {
          data.content = inner.content;
          if (inner.abstract) data.abstract = inner.abstract;
          if (inner.excerpt) data.excerpt = inner.excerpt;
        }
      }
    }

    // Fallback: If editor agent JSON format failed, construct a perfect structured object using raw LLM output
    if (!data || (!data.content && !raw)) {
      console.log(`[generate-content] Using robust multi-agent fallback constructor for topic: "${topic}"`);
      const cleanTitle = topic.replace(/[^\w\s-]/g, "").trim();
      const slug = `${type}-${cleanTitle.toLowerCase().replace(/\s+/g, "-")}-${Date.now().toString().slice(-4)}`;

      data = {
        slug,
        title: `${type === "research" ? "Research Paper: " : ""}${topic}`,
        excerpt: context.slice(0, 160).replace(/\n/g, " "),
        abstract: context.slice(0, 200).replace(/\n/g, " "),
        metaTitle: topic.slice(0, 60),
        metaDescription: topic.slice(0, 150),
        keywords: [topic.split(" ")[0] || "AI", "Multi-Agent", "Deep Learning", "Software Engineering"],
        date: today,
        readTime: "7 min read",
        tag: type === "research" ? "AI Research" : "Engineering",
        author: "Nabaraj KC",
        content: raw && raw.length > 200 ? raw.replace(/```json[\s\S]*```/g, "").trim() : `## ${topic}\n\nComprehensive exploration of ${topic}.\n\n${context}`,
        wordCount: (raw || context).split(/\s+/).length,
        generatedBy: "on-demand-ai",
        publishedAt: new Date().toISOString(),
      };
    } else if (!data.content && raw) {
      data.content = raw;
    }

    if (data.title) data.title = shortenTitle(data.title);
    if (data.content) data.wordCount = data.content.split(/\s+/).length;
    data.sources = sources.map((s: TavilyResult) => ({ title: s.title, url: s.url }));
    data.requestedBy = requestedBy;

    const existingSlug = await db.collection(collection).findOne({ slug: data.slug });
    if (existingSlug) data.slug = `${data.slug}-${Date.now()}`;

    data.published = true;
    data.status = "published";

    try {
      const coverUrl = await generateAndUploadCoverImage(
        data.keywords || [data.tag || "AI"],
        data.slug,
        type === "research" ? "autonomous/research" : "autonomous/articles",
        data.title,
        data.tag
      );
      if (coverUrl) data.coverImage = coverUrl;
    } catch (e) {
      console.warn("[generate-content] Cover image error:", e);
    }

    await db.collection(collection).insertOne(data);

    const url = type === "research" ? `/research/${data.slug}` : `/articles/${data.slug}`;

    return NextResponse.json({
      success: true,
      title: data.title,
      slug: data.slug,
      url,
      type,
      wordCount: data.wordCount,
      message: `Successfully generated and published: "${data.title}"`,
    });

  } catch (error: any) {
    console.error("Generate Content Error:", error);
    return NextResponse.json({ error: error.message || "Content generation failed." }, { status: 500 });
  }
}
